Naive Bayes

###### "Congratulations! You won $10,00,000". Click here now!

In [27]:
# Above Message is Spam.
    # It contains "won"
    # it contains "click here"
    # it promises "Money"

In [28]:
# What is Naive Bayes?
    # "Naive Bayes is a Probabilistic Classification Algorithm 
    # that predicts the class having the highest probability."

In [29]:
# Suppose there are 100 students.
    # 60 are Boys
    # 40 are Girls

# What is the probability of selecting Boy ? 
    # 60 % ==> 0.6


# Conditional Probability:
#     80 students wear spectacles.
#     Among those 80, 50 are boys


        # Q. What is the probability that a student is a boy,
        # given that the student wears spectacle.

        # P(Boy | Spectacles)

In [30]:
# Bayes Theorem:

    # P(A | B)

    # P(B | A)

In [31]:
# Naive :

        # All features are Independent.
        # This is called Naive Assumption

In [32]:
# Advantages : 
    # It is very Fast
    # Works well with small dataset
    # Excellent for test classification
    # Easy to implement
    # Requires less memory

# Disadvantages:
    # Assumes feature independence
    # Performance decreases if the independence assumption
    # is strongly voileted

In [33]:
# Imports:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [34]:
df =pd.read_csv("dataFiles/adult.csv")
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [35]:
# View Data

df.shape

(48842, 15)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  str
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  str
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  str
 6   occupation       48842 non-null  str
 7   relationship     48842 non-null  str
 8   race             48842 non-null  str
 9   gender           48842 non-null  str
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  str
 14  income           48842 non-null  str
dtypes: int64(6), str(9)
memory usage: 5.6 MB

In [37]:
# Check Missing Values

df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [38]:
df.replace(" ?", np.nan, inplace=True)
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [39]:
# Remove Missing Values:

df.dropna(inplace=True)

df.shape

(48842, 15)

In [40]:
# Separate Numerical and Categorical Columns:

df.select_dtypes(include="object").columns

C:\Users\SHIV PC\AppData\Local\Temp\ipykernel_2976\3333610291.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'gender', 'native-country', 'income'],
      dtype='str')

In [41]:
# Label Encoding:

encoder = LabelEncoder()

for column in df.select_dtypes(include="object").columns:
    df[column] = encoder.fit_transform(df[column])

C:\Users\SHIV PC\AppData\Local\Temp\ipykernel_2976\2377694123.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:

In [45]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,4,226802,1,7,4,7,3,2,1,0,0,40,39,0
1,38,4,89814,11,9,2,5,0,4,1,0,0,50,39,0
2,28,2,336951,7,12,2,11,0,4,1,0,0,40,39,1
3,44,4,160323,15,10,2,7,0,2,1,7688,0,40,39,1
4,18,0,103497,15,10,4,0,3,4,0,0,0,30,39,0

In [46]:
# Split Features and Targets:

X = df.drop("income", axis=1)
y = df["income"]

In [47]:
# Train Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [48]:
# Feature Scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [49]:
# Train Naive Bayes:

model = GaussianNB()

model.fit(X_train, y_train)

GaussianNB()

In [50]:
# Prediction:

y_pred = model.predict(X_test)

In [51]:
# Accuracy Check:

acc = accuracy_score(y_test, y_pred)
print(f"Acciracy: {acc}")

Acciracy: 0.8069403214249156

In [52]:
# Confusion Matrix:

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[7124  355]
 [1531  759]]

In [53]:
# Classification Report:

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.95      0.88      7479
           1       0.68      0.33      0.45      2290

    accuracy                           0.81      9769
   macro avg       0.75      0.64      0.66      9769
weighted avg       0.79      0.81      0.78      9769

In [54]:
# Preduict:
sample = X_test[0].reshape(1, -1)
Prediction = model.predict(sample)
print(Prediction)

[0]